### ISSUE TITLE
Forward reference inside image_tabular?

### ISSUE THREAD

**Issue by glitt13** [naity/image_tabular#1]
Using Python 3.8.3, fastai v2.1.10, and image_tabular v0.0.6 on Windows 10:

The following imports return an error:
```
import fastai
import image_tabular
from fastai.vision import *
from fastai.tabular import *
from image_tabular.core import *
```

The error is:
```
Traceback (most recent call last):

  File "<ipython-input-6-3fb4e005a29c>", line 7, in <module>
    from image_tabular.core import *

  File "C:\Users\username\Anaconda3\envs\fastai_env\lib\site-packages\image_tabular\core.py", line 19, in <module>
    def _normalize_batch_image_tab(b:Tuple[Tensor,Tensor],

NameError: name 'Tuple' is not defined
```

After review, it seems like this may be a [forward reference issue](https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class). I tried adding `from __future__ import annotations`  above `import fastai` because my python version is >3.7, but I still get the same error.

Similarly, `from image_tabular.dataset import *` yields `NameError: name 'Dataset' is not defined`, 
`from image_tabular.model import *` returns `NameError: name 'Module' is not defined`, and 
`from image_tabular.metric import *` returns `NameError: name 'Tensor' is not defined`.

Any advice on how I may fix these issues and use this neat looking tool?

Thanks!

**Comment by naity** [comment]
Thank you for your feedback. I'm sorry that the package is currently not compatible with fastai v2. I'll probably update the package in the near future.

**Comment by vikasmalik22** [comment]
Hi,
Can I check which fastai version is supported. I am currently using fastai 1.0.60. But still getting the above error Tuple is not defined. 
Thanks!

**Comment by naity** [comment]
Hi, you might be using a newer version of fastcore, which changed Tuple to fastuple.

**Comment by naity** [comment]
> Hi,
> Can I check which fastai version is supported. I am currently using fastai 1.0.60. But still getting the above error Tuple is not defined.
> Thanks!

Hi there, you might be using a newer version of fastcore, which changed Tuple to fastuple.

**Comment by SireeshLimbu** [comment]
Hi,

        I am also getting the same error. Is the package updated? If not, I was wondering if there is a workaround?

Thanks
